import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./navbar";
import { twMerge } from "tailwind-merge"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Image App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.className,
          "relative bg-white text-black dark:bg-black dark:text-white"
        )}
      >
        <header className="fixed left-0 right-0 bottom-0 sm:top-0 h-20 bg-white/80 dark:bg-black/80 backdrop-blur-xl z-10">
          <NavBar className="max-w-lg m-auto" />
        </header>
        <main className="mb-24 sm:mt-24 p-6 lg:p-0 m-auto max-w-lg z-0">{children}</main>
      </body>
    </html>
  );
}
